"""add table order_deliveries

Revision ID: a2f96ccea9e6
Revises: d4b9774cc9e2
Create Date: 2025-08-31 23:37:15.980396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f96ccea9e6'
down_revision: Union[str, None] = 'd4b9774cc9e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('desired_delivery_at', sa.Date(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('phone_primary', sa.String(), nullable=True),
    sa.Column('phone_secondary', sa.String(), nullable=True),
    sa.Column('extra_info', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_deliveries_id'), 'order_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_order_deliveries_order_id'), 'order_deliveries', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_deliveries_order_id'), table_name='order_deliveries')
    op.drop_index(op.f('ix_order_deliveries_id'), table_name='order_deliveries')
    op.drop_table('order_deliveries')
    # ### end Alembic commands ###
