"""article non unique for products

Revision ID: d4b9774cc9e2
Revises: e1700f8587ae
Create Date: 2025-02-05 16:22:52.396953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b9774cc9e2'
down_revision: Union[str, None] = 'e1700f8587ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_article', table_name='products')
    op.create_index(op.f('ix_products_article'), 'products', ['article'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_article'), table_name='products')
    op.create_index('ix_products_article', 'products', ['article'], unique=True)
    # ### end Alembic commands ###
